-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 16:52:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rep_sys_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rep_sys_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rep_sys_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `rep_sys_db` ;

-- -----------------------------------------------------
-- Table `rep_sys_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rep_sys_db`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(60) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rep_sys_db`.`error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rep_sys_db`.`error` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `description` TEXT(120) NULL,
  `text` LONGTEXT NULL,
  `uid` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `urgency` VARCHAR(45) NULL,
  `criticality` VARCHAR(45) NULL,
  PRIMARY KEY (`eid`),
  INDEX `user_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `user_e`
    FOREIGN KEY (`uid`)
    REFERENCES `rep_sys_db`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rep_sys_db`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rep_sys_db`.`Comment` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `action` VARCHAR(45) NULL,
  `body` TEXT(255) NULL,
  `eid` INT NULL,
  `uid` INT NULL,
  PRIMARY KEY (`cid`),
  INDEX `user_idx` (`uid` ASC) VISIBLE,
  INDEX `error_idx` (`eid` ASC) VISIBLE,
  CONSTRAINT `user_c`
    FOREIGN KEY (`uid`)
    REFERENCES `rep_sys_db`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `error_c`
    FOREIGN KEY (`eid`)
    REFERENCES `rep_sys_db`.`error` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
